color: purple
fieldLayouts:
  63634c0e-8e5a-46b9-88b4-01badbf9cb7c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9470e457-d996-4637-9b8c-6fb010f0e9f0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 965f7691-85e4-4299-9bbb-1496c625b05f # External URL
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 13cfa343-5ed1-4d7d-b600-49cc1e288def
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 68d329ca-2314-4981-bf9f-96c6353f1e07 # Single Line Text
            handle: caption
            includeInCards: true
            instructions: null
            label: Caption
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 900cf75e-4936-4594-916b-ff287e025556
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: b05c2a99-b877-4c2f-9682-2a010afca4d3 # Open in new Tab
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f3a6b942-39c4-431e-a852-db29c311c496
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: adc0b868-56f2-4a72-b425-dad228412d35
        userCondition: null
handle: externalLink
hasTitleField: false
icon: up-right-from-square
name: 'External Link'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
