color: green
fieldLayouts:
  22cc67d9-e2e7-4e8d-b385-a1bc4c43835e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ef8d76ef-d689-44c0-9d68-b21223330ec5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 68d329ca-2314-4981-bf9f-96c6353f1e07 # Single Line Text
            handle: text
            includeInCards: true
            instructions: null
            label: Text
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0890bafe-01df-4861-b2a2-10eb2ba54970
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: bdcd25ce-f3a8-48ae-ba57-0c83960a3fcd # Heading Level
            handle: null
            includeInCards: false
            instructions: null
            label: 'Heading Level'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f6856c6d-b5d4-43ce-ab12-c9e47511a9b5
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: be6789a7-64de-4d8d-a3a8-38a75763af9b
        userCondition: null
handle: heading
hasTitleField: false
icon: font
name: Heading
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
