fieldLayouts:
  abb633b6-3f52-4939-b871-3ea1ca602a5a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d9b8dacd-ca19-4b4d-89a7-5a0dc5587665
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7df417e8-1eea-46d8-85a7-2a20370a881e # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 73c4b57b-452b-4a9f-80d8-3bfda94d1366
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 85898001-9c9c-4d46-abf9-a928e44f0d48 # Body Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c6c3cce-2070-4b76-952c-51b7418cd702
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9bbb97bc-bb86-4feb-8333-b532e26b773c
        userCondition: null
handle: home
hasTitleField: true
name: Home
section: 6856c92d-c593-4425-8886-27e609d74667 # Home
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
