color: sky
fieldLayouts:
  73ac25bc-ace9-4aa6-ba1d-9211b5c06027:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 872ee4f3-fea0-4a6e-b30d-48f3743c2180
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 735b5e6e-8026-4de4-8e32-14e03d975565 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: Image
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9b2074e-9c0c-42ca-912b-da62df8b651a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\RelationalFieldConditionRule
                  elementId: null
                  fieldUid: 735b5e6e-8026-4de4-8e32-14e03d975565 # Image
                  layoutElementUid: c9b2074e-9c0c-42ca-912b-da62df8b651a
                  operator: notempty
                  uid: d9503954-8ebb-42e5-9b40-67d0612e6cb2
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 68d329ca-2314-4981-bf9f-96c6353f1e07 # Single Line Text
            handle: caption
            includeInCards: true
            instructions: null
            label: Caption
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dfb39309-ede6-4f5c-9edd-d4ccdd3ffd36
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: c7f52bda-4083-406b-982c-63def615500a
        userCondition: null
      -
        elementCondition:
          class: craft\elements\conditions\entries\EntryCondition
          conditionRules:
            -
              class: craft\fields\conditions\RelationalFieldConditionRule
              elementId: null
              fieldUid: 735b5e6e-8026-4de4-8e32-14e03d975565 # Image
              layoutElementUid: c9b2074e-9c0c-42ca-912b-da62df8b651a
              operator: notempty
              uid: 4d945754-d5bc-4f76-ac9e-3c469b8cc65c
          elementType: craft\elements\Entry
          fieldContext: global
        elements:
          -
            elementCondition: null
            fieldUid: a777a2b0-9e58-4e2e-b198-fdbeb8f10302 # Aspect Ratio
            handle: null
            includeInCards: true
            instructions: null
            label: 'Aspect Ratio'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3583c35d-cbcb-43d4-9ca9-6e52dd0d9e5f
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 8151138b-dc5d-40bf-b17d-831ab2d41eab # Crop
            handle: null
            includeInCards: false
            instructions: null
            label: Crop
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d135a0f8-be3a-4b3f-9a32-02f86b6412c7
            userCondition: null
            warning: null
            width: 25
        name: Style
        uid: 1000334f-a8dc-41d7-b0a9-bf33d1aa9489
        userCondition: null
handle: image
hasTitleField: false
icon: image-polaroid
name: Image
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
