color: blue
fieldLayouts:
  1841eaec-2449-41a7-b9b4-fd94a8e3498f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2aa25558-fb9f-4750-90b8-aee9c4421bd6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 33472095-00ea-40ee-8743-929c3c0978f8 # Entry
            handle: target
            includeInCards: true
            instructions: null
            label: Target
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7039b565-404f-4581-8eac-5a93fdbb569b
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 68d329ca-2314-4981-bf9f-96c6353f1e07 # Single Line Text
            handle: caption
            includeInCards: true
            instructions: 'Leave blank to use the entry''s title'
            label: Caption
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 889cbe3f-1cc4-4810-ac44-553bb981f893
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 35581e7d-7435-457c-8b60-e2ff810a6599
        userCondition: null
handle: link
hasTitleField: false
icon: bullseye-arrow
name: Link
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
