color: red
fieldLayouts:
  35aac453-6959-4771-9712-cb98f5a45da0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 23e88f1c-1490-4ee0-9514-ebc54e2dfce1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7df417e8-1eea-46d8-85a7-2a20370a881e # Featured Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f72d2e7e-3cde-4edf-82c4-0a50169808d4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e12cc90f-c692-4cac-8ff8-5fef33141ea4 # Teaser
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1fedead6-b598-4967-a083-352158ae3023
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\entries\SectionConditionRule
                  operator: ni
                  uid: 578b303c-e3a3-4c4a-9cd9-3d874affdbc7
                  values:
                    - a859ed7a-b179-4cb5-a9a1-6d2582b19eab # Post
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 85898001-9c9c-4d46-abf9-a928e44f0d48 # Body Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b3749e2b-fda8-411d-b55e-306b27632de2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\entries\SectionConditionRule
                  operator: in
                  uid: d2809b83-9624-4718-8868-80a62217447d
                  values:
                    - a859ed7a-b179-4cb5-a9a1-6d2582b19eab # Post
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 23b6659b-71e0-4166-95a8-4efb2bf76f40 # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: edb2088b-4047-4d80-9cdd-1b51eb42a56e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 805db790-0bd9-4591-905d-34133e531ece
        userCondition: null
handle: page
hasTitleField: true
icon: file
name: Page
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
