color: red
fieldLayouts:
  6a9bd8fb-02fb-47b3-aab3-cc85d6b04484:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8566dcae-4758-4735-98dd-4177a6c332f4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 59d53e5e-fc0b-4e78-9566-c7cb7342cefe # Multi Line Text
            handle: text
            includeInCards: true
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3fe8c56c-60d2-41c9-9eec-68a1644db2ae
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 68d329ca-2314-4981-bf9f-96c6353f1e07 # Single Line Text
            handle: source
            includeInCards: true
            instructions: null
            label: Source
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e470b9c-27d5-43ee-b1c7-941037095919
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 23b55a9d-c172-47e2-9dbc-1ccf3383b65e
        userCondition: null
handle: quote
hasTitleField: false
icon: quote-right
name: Quote
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
