fieldLayouts:
  b610ba0f-3699-420d-a62a-49b631e09bc2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3e35a043-a62e-4ede-acd6-44dfb92d6914 # Site Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0b7b855c-3f2f-4d39-8ef0-e5fccd7a2685
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: eb6b24cc-83d7-416f-be4b-d002c7688b58 # Copyright
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c5b5269f-b571-4e25-af4c-6cdfdc2fbf56
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bc563acf-2bf0-4e70-ad0b-0d9aff9906c7
        userCondition: null
handle: siteInfo
hasTitleField: false
name: 'Site Info'
section: 9e8a3f1b-ec7c-4c9a-9971-b65428c62592 # Site Info
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
