color: null
fieldLayouts:
  322df68d-3b25-4b3f-bcb5-730cfbbcbfbc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: eaa6d8a4-c4ec-4254-8a3d-be29c5b3855f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 59d53e5e-fc0b-4e78-9566-c7cb7342cefe # Multi Line Text
            handle: text
            includeInCards: true
            instructions: null
            label: Text
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c41b96ab-4f8d-4e36-9497-d94b60b6f3d1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 567dfff7-4e6b-43d6-bb7b-a486901aa8d8
        userCondition: null
handle: text
hasTitleField: false
icon: paragraph
name: Text
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
