columnSuffix: ygcxpixb
handle: aspectRatio
instructions: null
name: 'Aspect Ratio'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Auto
        -
          - value
          - auto
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '1:1'
        -
          - value
          - 1/1
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 16/9
        -
          - value
          - 16/9
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 10/8
        -
          - value
          - 10/8
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 21/9
        -
          - value
          - 21/9
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 7/5
        -
          - value
          - 7/5
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 4/3
        -
          - value
          - 4/3
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 5/3
        -
          - value
          - 5/3
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 3/2
        -
          - value
          - 3/2
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 3/1
        -
          - value
          - 3/1
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
