columnSuffix: null
handle: bodyContent
instructions: null
name: 'Body Content'
searchable: true
settings:
  entryTypes:
    - ac457f93-1a50-473e-9983-a899a7f0bed7 # Heading
    - 81e6a0d6-13c5-47ad-a9e6-c2181276db9c # Text
    - 69164545-5879-454d-a57e-f703ca431331 # Image
    - 052baf80-92b9-4d9d-889d-9326c028789b # Quote
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
