columnSuffix: ubjbhpop
handle: crop
instructions: null
name: Crop
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
