columnSuffix: null
handle: links
instructions: null
name: Links
searchable: true
settings:
  entryTypes:
    - 4e0d112b-0725-424f-a1e9-c088e67a2a70 # Link
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
