columnSuffix: yvfuijly
handle: siteName
instructions: null
name: 'Site Name'
searchable: false
settings:
  byteLimit: null
  charLimit: 30
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
