assets:
  tempVolumeUid: ed627edd-73bd-4b75-8684-f410bf4e4b9d # Temp Images
dateModified: 1700078212
elementSources:
  craft\elements\Asset:
    -
      heading: Site
      type: heading
    -
      disabled: false
      key: 'volume:5a0be839-14a2-465e-a504-bb63dd0281e9' # Images
      tableAttributes:
        - 'field:cc3fbab0-826f-4aed-b2aa-eeaecc2964bf' # Alt Text
        - imageSize
        - dateModified
        - link
      type: native
    -
      heading: Internal
      type: heading
    -
      disabled: false
      key: 'volume:ed627edd-73bd-4b75-8684-f410bf4e4b9d' # Temp Images
      tableAttributes:
        - 'field:cc3fbab0-826f-4aed-b2aa-eeaecc2964bf' # Alt Text
        - imageSize
        - dateModified
        - link
      type: native
    -
      disabled: false
      key: 'volume:3b60e4f9-36bb-4456-bee5-67160b5a3108' # User Photos
      tableAttributes:
        - 'field:cc3fbab0-826f-4aed-b2aa-eeaecc2964bf' # Alt Text
        - imageSize
        - dateModified
        - link
      type: native
  craft\elements\Entry:
    -
      key: '*'
      tableAttributes:
        - section
        - postDate
        - link
      type: native
    -
      heading: Site
      type: heading
    -
      defaultSort:
        - title
        - asc
      disabled: false
      key: singles
      tableAttributes:
        - section
        - drafts
        - 'field:7df417e8-1eea-46d8-85a7-2a20370a881e' # Featured Image
        - link
      type: native
    -
      key: 'section:84b98802-2548-4aed-b67e-fc97f6ed9e30' # Page
      tableAttributes:
        - drafts
        - type
        - 'field:7df417e8-1eea-46d8-85a7-2a20370a881e' # Featured Image
        - postDate
        - link
      type: native
email:
  fromEmail: $EMAIL_ADDRESS
  fromName: $EMAIL_SENDER
  replyToEmail: null
  template: ''
  transportSettings:
    encryptionMethod: $SMTP_ENCRYPTION_METHOD
    host: $SMTP_HOST
    password: $SMTP_PASSWORD
    port: $SMTP_PORT
    timeout: '10'
    useAuthentication: $SMTP_AUTHENTICATION
    username: $SMTP_USER
  transportType: craft\mail\transportadapters\Smtp
fs:
  imagesTransforms_local:
    hasUrls: true
    name: 'Images Transforms Local'
    settings:
      path: '@webroot/assets/transforms'
    type: craft\fs\Local
    url: '@web/assets/transforms'
  images_local:
    hasUrls: true
    name: 'Images Local'
    settings:
      path: '@webroot/files/images'
    type: craft\fs\Local
    url: '@web/files/images'
  tempimages_local:
    hasUrls: true
    name: 'Temp Images Local'
    settings:
      path: '@webroot/files/temp'
    type: craft\fs\Local
    url: '@web/files/temp'
  userPhotos_local:
    hasUrls: true
    name: 'User Photos Local'
    settings:
      path: '@webroot/files/userphotos'
    type: craft\fs\Local
    url: '@web/files/userphotos'
meta:
  __names__:
    3b60e4f9-36bb-4456-bee5-67160b5a3108: 'User Photos' # User Photos
    3bb09a1c-cb36-438e-b8d5-0b35b0965f4e: Default # Default
    3e35a043-a62e-4ede-acd6-44dfb92d6914: 'Site Name' # Site Name
    4b050685-0425-4094-bde2-85e2eedd0e12: Text # Text
    5a0be839-14a2-465e-a504-bb63dd0281e9: Images # Images
    5b0c38db-9ab4-47d8-b4a7-913710c08ca6: Default # Default
    7df417e8-1eea-46d8-85a7-2a20370a881e: 'Featured Image' # Featured Image
    9e2e3c4b-bd17-46b3-97f0-a4f6605b93d9: Text # Text
    9e8a3f1b-ec7c-4c9a-9971-b65428c62592: 'Site Info - Global Settings' # Site Info - Global Settings
    81e6a0d6-13c5-47ad-a9e6-c2181276db9c: Text # Text
    84b98802-2548-4aed-b67e-fc97f6ed9e30: Page # Page
    169ccd00-9c12-4921-b187-8ef8ca2ad525: Assets # Assets
    735b5e6e-8026-4de4-8e32-14e03d975565: Image # Image
    6856c92d-c593-4425-8886-27e609d74667: Home # Home
    69164545-5879-454d-a57e-f703ca431331: Image # Image
    85898001-9c9c-4d46-abf9-a928e44f0d48: 'Body Content' # Body Content
    abefa0bd-6b36-4b4f-a9de-a4304e7b66a3: 'Public Schema' # Public Schema
    ac457f93-1a50-473e-9983-a899a7f0bed7: Heading # Heading
    bd76fb6e-8765-41d3-8e8a-02e37e127c80: Common # Common
    c780bb7a-337c-46ba-95c4-c0dcbfcb457d: Home # Home
    cc3fbab0-826f-4aed-b2aa-eeaecc2964bf: 'Alt Text' # Alt Text
    d6f6663f-190b-40ff-b18b-36267fcf71f6: 'Site Info - Global Settings' # Site Info - Global Settings
    d50026f3-a236-4ae2-b00a-af55076acd17: Site # Site
    eb6b24cc-83d7-416f-be4b-d002c7688b58: Copyright # Copyright
    ed627edd-73bd-4b75-8684-f410bf4e4b9d: 'Temp Images' # Temp Images
    fbf00eb2-4a16-40ca-96bb-3fadd2bf459c: Default # Default
plugins:
  cp-css:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      additionalCss: "/* Set link color back to V3, increase contrast */\r\n:root {\r\n    --text-color: var(--gray-800);\r\n    --medium-dark-text-color: var(--gray-700);\r\n    --link-color: #0c4a6e;\r\n}\r\n\r\n/* Increase font size */\r\n\r\nhtml, body {\r\n    font-size: 16px !important;\r\n}\r\n\r\ninput.text, textarea.text, .text > input, .text > textarea, table.editable textarea, .selectize-text > .selectize-control > .selectize-input {\r\n    font-size: 16px !important;\r\n}\r\n\r\nh2 {\r\n    font-size: 18px !important;\r\n}\r\n\r\n/* We are not at a funeral */\r\n#global-sidebar {\r\n    background-color: #0c4a6e !important;\r\n}\r\n    \r\n\r\n#sidebar .heading > span {\r\n\r\n    font-size: 14px;\r\n}\r\n    \r\n\r\n/* 4.2 toasts */\r\n#notifications [data-type=\"error\"] {\r\n    background-color: #D61F2B;\r\n    color: white;\r\n}\r\n\r\n#notifications [data-type=\"success\"] {\r\n    background-color: #2C5F2D;\r\n    color: white;\r\n}\r\n\r\n#notifications [data-type=\"notice\"] {\r\n    background-color: #2C5F2D;\r\n    color: white;\r\n}\r\n\r\n#notifications .notification .notification-icon {\r\n    color: white;\r\n}\r\nbody.ltr #notifications {\r\n    bottom: initial;\r\n    top: 8px;\r\n    left: 50%;\r\n    transform: translateX(-50%);\r\n}\r\n#notifications .notification-details {\r\n    background-color: white;\r\n    padding: 4px;\r\n}"
      cacheBusting: true
      cssFile: ''
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: $SYSTEM_NAME
  retryDuration: 30
  schemaVersion: 4.5.3.0
  timeZone: $SYSTEM_TIMEZONE
users:
  allowPublicRegistration: false
  deactivateByDefault: false
  defaultGroup: ''
  photoSubpath: null
  photoVolumeUid: 3b60e4f9-36bb-4456-bee5-67160b5a3108 # User Photos
  requireEmailVerification: true
  validateOnPublicRegistration: false
