defaultPlacement: end
enableVersioning: true
entryTypes:
  - fbf00eb2-4a16-40ca-96bb-3fadd2bf459c # Page
handle: page
maxAuthors: 1
name: Page
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  5b0c38db-9ab4-47d8-b4a7-913710c08ca6: # Default
    enabledByDefault: true
    hasUrls: true
    template: _sections/page
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 90b11039-2eba-48d9-9e4a-bcbb8797204c
type: structure
